server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Servir OHIF
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy DICOMweb → Orthanc
    location /dicom-web {
        proxy_pass http://orthanc:8042/dicom-web;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        client_max_body_size 2048M;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    # Proxy WADO → Orthanc
    location /wado {
        proxy_pass http://orthanc:8042/wado;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        client_max_body_size 2048M;
        proxy_read_timeout 300s;
    }

    # Expor painel do Orthanc diretamente (opcional, remover em produção)
    location /orthanc/ {
        proxy_pass http://orthanc:8042/;
        proxy_set_header Host $host;
    }
}
